adjectives = ['Abrupt','Acidic','Adorable','Adventurous','Aggressive','Agitated',
'Alert','Aloof','Amiable','Amused','Annoyed','Antsy','Anxious','Appalling',
'Appetizing','Apprehensive','Arrogant','Ashamed','Astonishing','Attractive',
'Average','Batty','Beefy','Bewildered','Biting','Bitter','Bland','Blushing',
'Bored','Brave','Bright','Broad','Bulky','Burly','Charming','Cheeky','Cheerful',
'Chubby','Clean','Clear','Cloudy','Clueless','Clumsy','Colorful','Colossal',
'Combative','Comfortable','Condemned','Condescending','Confused','Contemplative',
'Convincing','Convoluted','Cooperative','Corny','Costly','Courageous','Crabby',
'Creepy','Crooked','Cruel','Cumbersome','Curved','Cynical','Dangerous','Dashing',
'Decayed','Deceitful','Deep','Defeated','Defiant','Delicious','Delightful','Depraved',
'Depressed','Despicable','Determined','Dilapidated','Diminutive','Disgusted','Distinct',
'Distraught','Distressed','Disturbed','Dizzy','Drab','Drained','Dull','Eager',
'Ecstatic','Elated','Elegant','Emaciated','Embarrassed','Enchanting','Encouraging',
'Energetic','Enormous','Enthusiastic','Envious','Exasperated','Excited','Exhilarated',
'Extensive','Exuberant','Fancy','Fantastic','Fierce','Filthy','Flat','Floppy','Fluttering',
'Foolish','Frantic','Fresh','Friendly','Frightened','Frothy','Frustrating','Funny',
'Fuzzy','Gaudy','Gentle','Ghastly','Giddy','Gigantic','Glamorous','Gleaming','Glorious',
'Gorgeous','Graceful','Greasy','Grieving','Gritty','Grotesque','Grubby','Grumpy','Handsome',
'Happy','Harebrained','Healthy','Helpful','Helpless','High','Hollow','Homely','Horrific',
'Huge','Hungry','Hurt','Icy','Ideal','Immense','Impressionable','Intrigued','Irate',
'Irritable','Itchy','Jealous','Jittery','Jolly','Joyous','Filthy','Flat','Floppy',
'Fluttering','Foolish','Frantic','Fresh','Friendly','Frightened','Frothy','Frustrating',
'Funny','Fuzzy','Gaudy','Gentle','Ghastly','Giddy','Gigantic','Glamorous','Gleaming',
'Glorious','Gorgeous','Graceful','Greasy','Grieving','Gritty','Grotesque','Grubby',
'Grumpy','Handsome','Happy','Harebrained','Healthy','Helpful','Helpless','High',
'Hollow','Homely','Horrific','Huge','Hungry','Hurt','Icy','Ideal','Immense',
'Impressionable','Intrigued','Irate','Irritable','Itchy','Jealous','Jittery','Jolly',
'Joyous','Juicy','Jumpy','Kind','Lackadaisical','Large','Lazy','Lethal','Little','Lively',
'Livid','Lonely','Loose','Lovely','Lucky','Ludicrous','Macho','Magnificent','Mammoth',
'Maniacal','Massive','Melancholy','Melted','Miniature','Minute','Mistaken','Misty',
'Moody','Mortified','Motionless','Muddy','Mysterious','Narrow','Nasty','Naughty',
'Nervous','Nonchalant','Nonsensical','Nutritious','Nutty','Obedient','Oblivious','Obnoxious',
'Odd','Outrageous','Panicky','Perfect','Perplexed','Petite','Petty','Plain','Pleasant',
'Poised','Pompous','Precious','Prickly','Proud','Pungent','Puny','Quaint','Quizzical',
'Ratty','Reassured','Relieved','Repulsive','Responsive','Ripe','Robust','Rotten','Rotund',
'Rough','Round','Salty','Sarcastic','Scant','Scary','Scattered','Scrawny','Selfish',
'Shaggy','Shaky','Shallow','Sharp','Shiny','Short','Silky','Silly','Skinny','Slimy',
'Slippery','Small','Smarmy','Smiling','Smoggy','Smooth','Smug','Soggy','Solid','Sore',
'Sour','Sparkling','Spicy','Splendid','Spotless','Square','Stale','Steady','Steep','Responsive',
'Sticky','Stormy','Stout','Straight','Strange','Strong','Stunning','Substantial','Successful',
'Succulent','Superficial','Superior','Swanky','Sweet','Tart','Tasty','Teeny','Tender',
'Tense','Terrible','Testy','Thankful','Thick','Thoughtful','Thoughtless','Tight',
'Timely','Tricky','Trite','Troubled','Twitter pated','Uneven','Unsightly','Upset',
'Uptight','Vast','Vexed','Victorious','Virtuous','Vivacious','Vivid','Wacky','Weary',
'Whimsical','Whopping','Wicked','Witty','Wobbly','Wonderful','Worried','Yummy','Zany',
'Zealous','Zippy']

nouns = ['Apple','Air','Conditioner','Airport','Ambulance','Aircraft','Apartment','Arrow',
'Antlers','Apro','Alligator','Architect','Ankle','Armchair','Aunt','Ball','Bermudas','Beans',
'Balloon','Bear','Blouse','Bed','Bow','Bread','Black','Board','Bones','Bill','Bitterness',
'Boxers','Belt','Brain','Buffalo','Bird','Baby','Book','Back','Butter','Bulb','Buckles',
'Bat','Bank','Bag','Bra','Boots','Blazer','Bikini','Bookcase','Bookstore','Busstop','Brass',
'Brother','Boy','Blender','Bucket','Bakery','Bow','Bridge','Boat','Car','Cow','Cap','Cooker',
'Cheeks','Cheese','Credenza','Carpet','Crow','Crest','Chest','Chair','Candy','Cabinet','Cat',
'Coffee','Children','Cookware','ChaiseLongue','Chicken','Casino','Cabin','Castle','Church',
'Cafe','Cinema','Choker','Cravat','Cane','Costume','Cardigan','Chocolate','Crib','Couch',
'Cello','Cashier','Composer','Cave','Country','Computer','Canoe','Clock','Dog','Deer','Donkey',
'Desk','Desktop','Dress','Dolphin','Doctor','Dentist','Drum','Dresser','Designer','Detective',
'Daughter','Egg','Elephant','Earrings','Ears','Eyes','Estate','Finger','Fox','Frock','Frog',
'Fan','Freezer','Fish','Film','Foot','Flag','Factory','Father','Farm','Forest','Flower',
'Fruit','Fork','Grapes','Goat','Gown','Garlic','Ginger','Giraffe','Guava','Grains','Garage',
'Gloves','Glasses','Gift','Galaxy','Guitar','Grandmother','Grandfather','Governor','Girl','Guest',
'Hamburger','Hand','Head','Hair','Heart','House','Horse','Hen','Horn','Hat','Hammer','Hostel',
'Hospital','Hotel','Heels','Herbs','Host','Jacket','Jersey','Jewelry','Jaw','Jumper','Judge',
'Juicer','Keyboard','Kid','Kangaroo','Koala','Knife','Lemon','Lion','Leggings','Leg','Laptop',
'Library','Lamb','London','Lips','Lung','Lighter','Luggage','Lamp','Lawyer','Mouse','Monkey',
'Mouth','Mango','Mobile','Milk','Music','Mirror','Musician','Mother','Man','Model','Mall',
'Museum','Market','Moonlight','Medicine','Microscope','Newspaper','Nose','Notebook','Neck',
'Noodles','Nurse','Necklace','Noise','Ocean','Ostrich','Oil','Orange','Onion','Oven','Owl',
'Paper','Panda','Pants','Palm','Pasta','Pumpkin','Pharmacist','Potato','Parfume','Panther',
'Pad','Pencil','Pipe','Police','Pen','Pharmacy','Parrot','Plane','Pigeon','Phone','Peacock',
'Pencil','Pig','Pouch','Pagoda','Pyramid','Purse','Pancake','Popcorn','Piano','Physician',
'Photographer','Professor','Painter','Park','Plant','Parfume','Radio','Razor','Ribs','Rainbow',
'Ring','Rabbit','Rice','Refrigerator','Remote','Restaurant','Road','Surgeon','Scale','Shampoo',
'Sink','Salt','Shark','Sandals','Shoulder','Spoon','Soap','Sand','Sheep','Sari','Stomach',
'Stairs','Soup','Shoes','Scissors','Sparrow','Shirt','Suitcase','Stove','Stairs','Snowman','Shower',
'Swan','Suit','Sweater','Smoke','Skirt','Sofa','Socks','Stadium','Skyscraper','School','Sunglasses',
'Sandals','Slippers','Shorts','Sandwich','Strawberry','Spaghetti','Shrimp','Saxophone','Sister',
'Son','Singer','Senator','Street','Supermarket','Star','Sky','Sun','Spoon','Ship','Smile',
'Table','Turkey','Tie','Toes','Truck','Train','Taxi','Tiger','Trousers','Tongue','Television',
'Teacher','Turtle','Tablet','Toothpaste','Tail','Theater','Tea','Tomato','Teen','Tunnel',
'Temple','Town','Toothbrush','Tree','Toy','Tissue','Telephone','Underwear','Uncle',
'Umbrella','Vest','Voice','Veterinarian','Villa','Violin','Village','Vehicle','Vase','Wallet',
'Wolf','Waist','Wrist','Watermelon','Whale','Water','Wings','Whisker','Watch','Woman',
'Wheelchair','Waiter','Wound','Xylophone','Zebra','Zoo']

animals = ['Aardvark','Albatross','Alligator','Alpaca','Anole','Ant','Anteater','Antelope',
'Ape','Armadillo ','Baboon','Badger','Barracuda','Bat','Bear','Beaver','Bee','Binturong','Bird ',
'Bison','Bluebird','Boar','Bobcat','Budgerigar','Buffalo','Butterfly','Camel','Capybara','Caracal',
'Caribou','Cassowary','Cat','Caterpillar','Cattle','Chamois','Cheetah','Chicken','Chimpanzee',
'Chinchilla','Chough','Coati','Cobra','Cockroach','Cod','Cormorant','Cougar','Coyote','Crab',
'Crane','Cricket','Crocodile','Crow','Cuckoo','Curlew','Deer','Dhole','Dingo','Dinosaur',
'Dog','Dogfish','Dolphin','Donkey','Dove','Dragonfly','Duck','Dugong','Dunlin','Eagle',
'Echidna','Eel','Eland','Elephant','Elephant seal','Elk','Emu','Falcon','Ferret','Finch',
'Fish','Fisher','Flamingo','Fly','Flycatcher','Fox','Frog','Gaur','Gazelle','Gecko','Genet',
'Gerbil','Giant panda','Giraffe','Gnat','Gnu','Goat','Goldfinch','Goosander','Goose','Gorilla',
'Goshawk','Grasshopper','Grouse','Guanaco','Guinea fowl','Guinea pig','Gull','Hamster','Hare',
'Hawk','Hedgehog','Hermit crab','Heron','Herring','Hippopotamus','Hoatzin','Hoopoe','Hornet',
'Horse','Human','Hummingbird','Hyena','Ibex','Ibis','Iguana','Impala','Jackal','Jaguar','Jay',
'Jellyfish','Jerboa','Kangaroo','Kingbird','Kingfisher','Kinkajou','Kite','Koala','Kodkod',
'Komodo dragon','Kookaburra','Kouprey','Kudu','Ladybird','Langur','Lapwing','Lark','Lechwe',
'Lemur','Leopard','Lion','Lizard','Llama','Lobster','Locust','Loris','Louse','Lynx','Lyrebird',
'Macaque','Macaw','Magpie','Mammoth','Manatee','Mandrill','Margay','Marmoset','Marmot',
'Meerkat','Mink','Mole','Mongoose','Monkey','Moose','Mosquito','Mouse','Myna','Narwhal','Newt',
'Nightingale','Nilgai','Ocelot','Octopus','Okapi','Oncilla','Opossum','Orangutan','Oryx','Ostrich',
'Otter','Ox','Owl','Oyster','Panther','Parrot','Panda','Partridge','Peafowl','Penguin','Pheasant',
'Pig','Pigeon','Pika','Polar bear','Pony','Porcupine','Porpoise','Prairie dog','Pug','Quail',
'Quelea','Quetzal','Rabbit ','Raccoon','Ram','Rat ','Raven','Red deer','Red panda','Reindeer',
'Rhea','Rhinoceros','Rook','Saki','Salamander','Salmon','Sand dollar','Sandpiper','Sardine',
'Sassaby','Sea lion','Seahorse','Seal','Serval','Shark','Sheep','Shrew','Shrike','Siamang',
'Skink','Skipper','Skunk','Sloth','Snail','Snake  ','Spider  ','Spoonbill','Squid','Squirrel',
'Starling','Stilt','Swan','Tamarin','Tapir','Tarsier','Termite','Thrush','Tiger','Toad','Topi',
'Toucan','Turaco','Turkey ','Turtle','Uakari','Umbrellabird','Unicornfish','Urial','Vicuña',
'Vinegaroon','Viper','Viperfish','Vireo','Viscacha','Vole','Vulture','Wallaby','Walrus','Wasp',
'Water buffalo','Waxwing','Weasel','Whale','Wobbegong','Wolf','Wolverine','Wombat','Woodpecker',
'Worm','Wren','Yak','Zebra']

colours = ['Aero','Alabaster','Almond','Amaranth','Amazon','Amber','Amethyst','Apricot','Aqua',
'Aquamarine','Artichoke','Asparagus','Auburn','Aureolin','Avocado','Azure','Beaver','Beige',
'Bisque','Bistre','Bittersweet','Black','Blond','Blue','Bluetiful','Blush','Bole','Bone','Brandy',
'Bronze','Brown','Buff','Burgundy','Burlywood','Byzantine','Byzantium','Cadet','Camel','Canary',
'Capri','Cardinal','Carmine','Carnelian','Catawba','Celadon','Celeste','Cerise','Cerulean',
'Champagne','Charcoal','Chestnut','Cinereous','Cinnabar','Citrine','Citron','Claret','Coffee',
'Copper','Coquelicot','Coral','Cordovan','Corn','Cornsilk','Cream','Crimson','Crystal','Cultured',
'Cyan','Cyclamen','Denim','Desert','Drab','Ebony','Ecru','Eggplant','Eggshell','Eigengrau',
'Emerald','Eminence','Erin','Fallow','Fandango','Fawn','Feldgrau','Firebrick','Flame','Flax',
'Flirt','Frostbite','Fuchsia','Fulvous','Gainsboro','Gamboge','Glaucous','Gold','Goldenrod',
'Green','Grullo','Gunmetal','Harlequin','Heliotrope','Honeydew','Iceberg','Icterine','Inchworm',
'Independence','Indigo','Iris','Irresistible','Isabelline','Ivory','Jade','Jasmine','Jet',
'Jonquil','Keppel','Kobe','Kobi','Kobicha','Lava','Lemon','Liberty','Lilac','Linen','Lion',
'Liver','Livid','Magenta','Magnolia','Mahogany','Maize','Malachite','Manatee','Mandarin','Mango',
'Mantis','Marigold','Mauve','Mauvelous','Melon','Midnight','Mindaro','Ming','Mint','Mulberry',
'Mustard','Mystic','Nickel','Nyanza','Ochre','Olive','Olivine','Onyx','Opal','Orange','Orchid',
'Oxblood','Parchment','Patriarch','Peach','Pear','Periwinkle','Persimmon','Phlox','Pink','Pistachio',
'Platinum','Plum','Popstar','Prune','Puce','Pumpkin','Purple','Purpureus','Rajah','Raspberry',
'Razzmatazz','Red','Redwood','Rhythm','Rose','Rosewood','Ruber','Ruby','Rufous','Russet','Rust',
'Saffron','Sage','Salmon','Sand','Sapphire','Scarlet','Seashell','Sepia','Shadow','Sienna','Silver',
'Sinopia','Skobeloff','Smitten','Snow','Straw','Strawberry','Sunglow','Sunray','Sunset','Tan',
'Tangerine','Taupe','Teal','Telemagenta','Thistle','Timberwolf','Tomato','Tumbleweed','Turquoise',
'Tuscan','Tuscany','Ultramarine','Umber','Vanilla','Verdigris','Vermilion','Vermilion','Veronica',
'Violet','Viridian','Volt','Wheat','White','Wine','Wisteria','Xanadu','Xanthic','Xanthous','Yellow',
'Zaffre','Zomp']